const timeline=document.querySelector('#timeline'),stats=document.querySelector('#stats'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),resultCount=document.querySelector('#resultCount');
let active='all';
const categories=['all','mount','guard','sweep','armbar','takedown'];
const list=x=>`<ul>${x.map(v=>`<li>${v}</li>`).join('')}</ul>`;
function renderStats(){const total=sessions.reduce((a,s)=>a+s.minutes,0);stats.innerHTML=[['Sessions',sessions.length],['Rolling minutes',total],['Techniques seen',techniques.length],['Current KPI','Survive longer']].map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('')}
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="filter ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderFilters();renderSessions()})}
function renderSessions(){const q=search.value.trim().toLowerCase();const rows=sessions.slice().reverse().filter(s=>{const hay=JSON.stringify(s).toLowerCase();return(active==='all'||hay.includes(active))&&(!q||hay.includes(q))});resultCount.textContent=`${rows.length} session${rows.length===1?'':'s'}`;timeline.innerHTML='';if(!rows.length){timeline.innerHTML='<div class="empty">Không thấy gì. Có khi technique này mày chưa học thật =))))</div>';return}rows.forEach(s=>{const t=document.querySelector('#sessionTemplate').content.cloneNode(true);t.querySelector('.session-kicker').textContent=`SESSION ${String(s.n).padStart(2,'0')} · ${s.date}`;t.querySelector('h3').textContent=s.title;t.querySelector('.session-meta').innerHTML=`${s.minutes} min roll<br>${s.intensity}<div class="tags">${s.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div>`;t.querySelector('.learned').innerHTML=list(s.learned);t.querySelector('.roll').innerHTML=list(s.roll);t.querySelector('.worked').innerHTML=list(s.worked);t.querySelector('.lost').innerHTML=list(s.lost);t.querySelector('.focus').append(document.createTextNode(s.focus));timeline.append(t)})}
function renderLibrary(){document.querySelector('#library').innerHTML=techniques.map(([name,lvl,label])=>`<div class="tech"><h3>${name}</h3><div class="level"><i style="width:${lvl*25}%"></i></div><small>${label}</small></div>`).join('')}
search.addEventListener('input',renderSessions);renderStats();renderFilters();renderSessions();renderLibrary();
