const timeline=document.querySelector('#timeline'),stats=document.querySelector('#stats'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),resultCount=document.querySelector('#resultCount'),dialog=document.querySelector('#techDialog'),techDetail=document.querySelector('#techDetail');
let active='all';
const categories=['all','mount','guard','sweep','armbar','takedown'];
const survivalKit=['ELBOW IN → KNEE IN','Protect neck first','Get one knee inside','Mount escape: find space, then move','C-cup → cross arm → turn → under leg → sweep'];
const defaultRefs={
  'Mount escape':[], 'Knee-to-elbow':[], 'Closed guard':[], 'Single Leg X':[], 'Spider guard':[], 'Straight ankle lock':[], 'Armbar defense':[], 'Closed-guard sweep chain':[], 'Knee on belly':[], 'S-mount':[], 'Canto choke':[], 'Bow & arrow choke':[], 'Seat belt':[], 'Kimura':[], 'Americana':[]
};
const savedRefs=JSON.parse(localStorage.getItem('dl-bjj-refs')||'{}');
const refsFor=name=>savedRefs[name]||defaultRefs[name]||[];
const saveRefs=()=>localStorage.setItem('dl-bjj-refs',JSON.stringify(savedRefs));
const list=x=>`<ul>${x.map(v=>`<li>${v}</li>`).join('')}</ul>`;
function renderStats(){const total=sessions.reduce((a,s)=>a+s.minutes,0);stats.innerHTML=[['Sessions',sessions.length],['Rolling minutes',total],['Techniques seen',techniques.length],['Current KPI','Survive longer']].map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('')}
function renderSurvival(){document.querySelector('#survivalKit').innerHTML=survivalKit.map(x=>`<span class="survival-pill">${x}</span>`).join('')}
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="filter ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderFilters();renderSessions()})}
function renderSessions(){const q=search.value.trim().toLowerCase();const rows=sessions.slice().reverse().filter(s=>{const hay=JSON.stringify(s).toLowerCase();return(active==='all'||hay.includes(active))&&(!q||hay.includes(q))});resultCount.textContent=`${rows.length} session${rows.length===1?'':'s'}`;timeline.innerHTML='';if(!rows.length){timeline.innerHTML='<div class="empty">Không thấy gì. Có khi technique này mày chưa học thật =))))</div>';return}rows.forEach(s=>{const t=document.querySelector('#sessionTemplate').content.cloneNode(true);t.querySelector('.session-kicker').textContent=`SESSION ${String(s.n).padStart(2,'0')} · ${s.date}`;t.querySelector('h3').textContent=s.title;t.querySelector('.session-meta').innerHTML=`${s.minutes} min roll<br>${s.intensity}`;t.querySelector('.tags').innerHTML=s.tags.map(x=>`<span class="tag">${x}</span>`).join('');const summary=[['LEARNED',s.learned[0]],['ROLL',s.roll[0]],['WORKED',s.worked[0]],['STILL LOST',s.lost[0]]];t.querySelector('.session-summary').innerHTML=summary.map(([k,v])=>`<div class="summary-chip"><b>${k}</b><span>${v}</span></div>`).join('');t.querySelector('.focus').append(document.createTextNode(s.focus));t.querySelector('.session-details').innerHTML=`<div class="detail-grid"><div><h4>LEARNED</h4>${list(s.learned)}</div><div><h4>WHAT HAPPENED IN ROLL</h4>${list(s.roll)}</div><div><h4>WHAT WORKED</h4>${list(s.worked)}</div><div><h4>STILL LOST HERE</h4>${list(s.lost)}</div></div>`;const btn=t.querySelector('.details-btn'),details=t.querySelector('.session-details');btn.onclick=()=>{details.hidden=!details.hidden;btn.textContent=details.hidden?'Open full notes ↓':'Close full notes ↑'};timeline.append(t)})}
function openTechnique(name,lvl,label){const refs=refsFor(name);techDetail.innerHTML=`<p class="eyebrow">TECHNIQUE</p><h2>${name}</h2><div class="level"><i style="width:${lvl*25}%"></i></div><p><b>${label}</b></p><div class="ref-list">${[0,1,2].map(i=>{const r=refs[i];return `<div class="ref-row"><div>${r?`<a href="${r.url}" target="_blank" rel="noopener">${r.title||'Reference clip '+(i+1)}</a>`:`<span>Reference clip ${i+1} · chưa set</span>`}</div><button class="replace-ref" data-i="${i}">${r?'Replace':'Add clip'}</button></div>`}).join('')}</div><p class="ref-note">Video mày thay ở đây được lưu trên browser này. Khi mày đưa tao clip ngon hơn, tao cũng có thể update bản chính trên site.</p>`;techDetail.querySelectorAll('.replace-ref').forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.i;const url=prompt('Paste video URL');if(!url)return;const title=prompt('Tên clip (optional)')||`My reference ${i+1}`;const arr=[...refsFor(name)];arr[i]={title,url};savedRefs[name]=arr;saveRefs();openTechnique(name,lvl,label)});if(!dialog.open)dialog.showModal()}
function renderLibrary(){document.querySelector('#library').innerHTML=techniques.map(([name,lvl,label])=>`<div class="tech" data-name="${name}"><h3>${name}</h3><div class="level"><i style="width:${lvl*25}%"></i></div><small>${label} · ${refsFor(name).filter(Boolean).length}/3 refs</small></div>`).join('');document.querySelectorAll('.tech').forEach(el=>{const row=techniques.find(x=>x[0]===el.dataset.name);el.onclick=()=>openTechnique(...row)})}
document.querySelector('.close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});search.addEventListener('input',renderSessions);renderStats();renderSurvival();renderFilters();renderSessions();renderLibrary();
